#!/bin/bash

MYSQL_HOST="$MYSQL_HOST"
MYSQL_PORT="$MYSQL_PORT"
MYSQL_USERNAME="$MYSQL_USERNAME"
MYSQL_PASSWORD="$MYSQL_PASSWORD"
MYSQL_SCHEMA="$MYSQL_SCHEMA"
BASTION_HOST="$BASTION_HOST"
BASTION_USERNAME="$BASTION_USERNAME"
TUNNELING_PORT=30010

echo "Running initdb.sh"

chmod 600 /bastion.pem
ssh -i bastion.pem -CNf -L $TUNNELING_PORT:$MYSQL_HOST:$MYSQL_PORT $BASTION_USERNAME@$BASTION_HOST -o StrictHostKeyChecking=no

mysql -h 127.0.0.1 -P $TUNNELING_PORT -u $MYSQL_USERNAME -p$MYSQL_PASSWORD -D $MYSQL_SCHEMA < /sqls/cleanup.sql
mysql -h 127.0.0.1 -P $TUNNELING_PORT -u $MYSQL_USERNAME -p$MYSQL_PASSWORD -D $MYSQL_SCHEMA < /sqls/initdata.sql

echo "Sleeping for 15 seconds..."
sleep 15